name = "BrunoCastroIbarburu"
uuid = "e06fa01e-879f-4c02-aae1-e5bac33212fc"
authors = ["Bruno Castro Ibarburu"]
version = "0.0.1"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
